name = "from-the-hart-tech-api-reverse-proxy-worker"
main = "src/index.ts"
compatibility_date = "2025-04-14"
workers_dev = false

[triggers]
crons = []

[build]
command = "npm run build"

# Local environment configuration
[env.local]
vars = { API_GATEWAY_ORIGIN = "uy4sjtmphp7hhpr3lsky75rgfy0qkptg.lambda-url.af-south-1.on.aws" }

# Dev environment configuration
[env.dev]
vars = { API_GATEWAY_ORIGIN = "fl0hv7pdrh.execute-api.af-south-1.amazonaws.com" }

[[env.dev.routes]]
pattern = "dev-api.fromthehart.tech"
custom_domain = true

# Prod environment configuration
[env.prod]
vars = { API_GATEWAY_ORIGIN = "q3d5ewqlcb.execute-api.af-south-1.amazonaws.com" }

[[env.prod.routes]]
pattern = "api.fromthehart.tech"
custom_domain = true

[observability.logs]
enabled = true