name = "from-the-hart-tech-api-reverse-proxy-worker"
main = "src/index.ts"
compatibility_date = "2025-03-10"
workers_dev = false

[triggers]
crons = []

[build]
command = "npm run build"

# Local environment configuration
[env.local]
vars = { ENVIRONMENT = "local" }

# Dev environment configuration
[env.dev]
vars = { ENVIRONMENT = "dev" }
[[env.dev.routes]]
pattern = "dev-api.fromthehart.tech"
custom_domain = true

# Prod environment configuration
[env.prod]
vars = { ENVIRONMENT = "prod" }
[[env.prod.routes]]
pattern = "api.fromthehart.tech"
custom_domain = true

[observability.logs]
enabled = true

[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 10, period = 60 }