name = "from-the-hart-tech-api-reverse-proxy-worker"
main = "src/index.ts"
compatibility_date = "2025-10-21"
workers_dev = false

[triggers]
crons = []

[build]
command = "npm run build"

# Local environment configuration
[env.local]
vars = { ENVIRONMENT = "local" }
[[env.local.ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1001"
simple = { limit = 2, period = 60 }

# Dev environment configuration
[env.dev]
vars = { ENVIRONMENT = "dev" }
[[env.dev.routes]]
pattern = "dev-api.fromthehart.tech"
custom_domain = true
[[env.dev.ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1001"
simple = { limit = 10, period = 60 }

# Prod environment configuration
[env.prod]
vars = { ENVIRONMENT = "prod" }
[[env.prod.routes]]
pattern = "api.fromthehart.tech"
custom_domain = true
[[env.prod.ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1001"
simple = { limit = 20, period = 60 }

[observability.logs]
enabled = true